image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - 42Crunch.vscode-openapi

tasks:
  - name: Setup tools
    init: |-
      go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest
      go install honnef.co/go/tools/cmd/staticcheck@latest

  - name: Init Terraform
    init: |-
      make terraform-init

  - name: Init Packer
    init: |-
      make init-cluster-image

github:
  prebuilds:
    branches: true
