image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - dbaeumer.vscode-eslint
    - errata-ai.vale-server

tasks:
  - name: Setup tools
    init: |-
      go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest
      go install honnef.co/go/tools/cmd/staticcheck@latest
      go install github.com/goreleaser/goreleaser@latest
      
  - name: Init Terraform
    init: |-
      make terraform-init

  - name: Init Packer
    init: |-
      cd ./packages/cluster-disk-image && make init

  - name: Init Styles
    init: vale sync

github:
  prebuilds:
    branches: true
