image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - hashicorp.terraform

tasks:
  - name: Setup
    init: |-
      go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest
      go install honnef.co/go/tools/cmd/staticcheck@latest

github:
  prebuilds:
    branches: true
