image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - hashicorp.terraform

tasks:
  - init: cd api && make build
  - init: cd orch
  - init: cd ifra
  - init: cd env
