project_name: devbookd
before:
  hooks:
    - go mod tidy
builds:
  - id: devbookd
    binary: devbookd
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64

archives:
  - id: latest
    builds:
      - devbookd
    wrap_in_directory: false
    format: tar.gz
    name_template: "devbookd_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

changelog:
  skip: true

release:
  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  prerelease: auto

snapshot:
  name_template: "{{ .Branch }}-{{ .ShortCommit }}"

checksum:
  name_template: 'checksums.txt'

#nfpms:
#  - maintainer: Devbook
#    description: Devbook Daemon
#    homepage: https://github.com/devbookhq/devbookd
#    license: MIT
#    formats:
#      - apk
#      - deb
#      - rpm