project_name: devbookd
before:
  hooks:
    - go mod tidy
builds:
  - id: devbookd
    binary: devbookd
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
changelog:
  skip: true

release:
  prerelease: auto

checksum:
  name_template: 'checksums.txt'

nfpms:
  - maintainer: Devbook
    description: Devbook Daemon
    homepage: https://github.com/devbookhq/devbookd
    license: MIT
    formats:
      - apk
      - deb
      - rpm