openapi: 3.0.0
info:
  version: 1.0.0
  title: Devbook
  description: Devbook API

tags:
  - name: sessions
    description: Managing VM sessions
  - name: envs
    description: Environment for VM
  - name: envevals
    description: Status of the job building the environment


components:
  #securitySchemes:
  #  ApiKeyAuth: # Arbitrary name for the security scheme
  #    type: apiKey
  #    in: query # Can be 'header', 'query' or 'cookie'
  #    name: API_KEY # Name of the header, query parameter or cookie
  schemas:
    AnyValue: {}
    NewEnvironment:
      type: object
      required:
        - codeSnippetID
        - runtime
        - deps
      properties:
        codeSnippetID:
          type: string
        runtime:
          type: string
          enum: [nodejs]
        deps:
          type: array
          items:
            type: string
    Environment:
      allOf:
        - $ref: '#/components/schemas/NewEnvironment'
        - type: object
          required:
            - status
          properties:
            status:
              type: string
              enum: [building, failed, done]
    EnvironmentStatus:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum: [building, failed, done]

      #NewEnvironment:
      #  required:
      #    - codeSnippetID
      #    - runtime
      #    - deps
      #  properties:
      #    codeSnippetID:
      #      type: string
      #      description: Identifier of a code snippet which which is the environment associated
      #    runtime:
      #      type: string
      #      enum: [nodejs]
      #    deps: # ['dep1', 'dep2']
      #      type: array
      #      items:
      #        type: string
      #  Environment:
      #    required:
      #      - codeSnippetID
      #      - r

    Session:
      required:
        - session_id
      properties:
        session_id:
          type: string
          description: Identifier of the session
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error

#security:
  #- ApiKeyAuth: [] # Use the same name as under securitySchemes

paths:
  /:
    get:
      description: Health check
      responses:
        '200':
          description: Request was successful
  /sessions:
    get:
      tags:
        - sessions
      description: List all sessions
      responses:
        '200':
          description: Successfully returned all sessions
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/AnyValue'

        '500':
          description: Error listing sessions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags:
        - sessions
      description: Create a session on the server

      responses:
        '200':
          description: Successfully created a session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'

        '500':
          description: Error creating session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /sessions/{session_id}:
    delete:
      tags:
        - sessions
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
      description: Delete a session on the server
      responses:
        '200':
          description: Successfully deleted a session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'

        '500':
          description: Error deleting session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /envs:
    post:
      tags:
        - envs
      responses:
        200:
          description: Successfully created an environment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewEnvironment'
  /envs/{envID}:
    get:
      tags:
        - envs
      parameters:
        - name: envID
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Environment'
  /envs/{envID}/status:
    post:
      tags:
        - envs
      parameters:
        - name: envID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnvironmentStatus'

