openapi: 3.0.0
info:
  version: 1.0.0
  title: Devbook
  description: Devbook API

tags:
  - name: sessions
    description: Managing VM sessions
  - name: envs
    description: Environment for VM
  - name: envevals
    description: Status of the job building the environment

components:
  #securitySchemes:
  #  ApiKeyAuth: # Arbitrary name for the security scheme
  #    type: apiKey
  #    in: query # Can be 'header', 'query' or 'cookie'
  #    name: API_KEY # Name of the header, query parameter or cookie
  schemas:
    NewEnvironment:
      type: object
      required:
        - codeSnippetID
        - runtime
        - deps
      properties:
        codeSnippetID:
          type: string
        runtime:
          type: string
          enum: [Nodejs]
        deps:
          type: array
          items:
            type: string
    Environment:
      allOf:
        - $ref: "#/components/schemas/NewEnvironment"
        - type: object
          required:
            - id
            - status
          properties:
            id:
              type: string
            status:
              type: string
              enum: [Building, Failed, Done]
    EnvironmentStatus:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum: [Building, Failed, Done]

      #NewEnvironment:
      #  required:
      #    - codeSnippetID
      #    - runtime
      #    - deps
      #  properties:
      #    codeSnippetID:
      #      type: string
      #      description: Identifier of a code snippet which which is the environment associated
      #    runtime:
      #      type: string
      #      enum: [nodejs]
      #    deps: # ['dep1', 'dep2']
      #      type: array
      #      items:
      #        type: string
      #  Environment:
      #    required:
      #      - codeSnippetID
      #      - r

    NewSession:
      required:
        - codeSnippetID
      properties:
        codeSnippetID:
          type: string
          description: Identifier of a code snippet which which is the environment associated
    Session:
      required:
        - sessionID
        - clientID
      properties:
        sessionID:
          type: string
          description: Identifier of the session
        clientID:
          type: string
          description: Identifier of the client

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error

#security:
#- ApiKeyAuth: [] # Use the same name as under securitySchemes

paths:
  /:
    get:
      description: Health check
      responses:
        200:
          description: Request was successful
  /sessions:
    get:
      tags:
        - sessions
      description: List all sessions
      responses:
        200:
          description: Successfully returned all sessions
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: "#/components/schemas/Session"
        500:
          description: Error listing sessions
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      tags:
        - sessions
      description: Create a session on the server
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewSession"
      responses:
        201:
          description: Successfully created a session
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Session"
        400:
          description: Bad request body format
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Error creating session
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /sessions/{sessionID}:
    delete:
      tags:
        - sessions
      parameters:
        - name: sessionID
          in: path
          required: true
          schema:
            type: string
      description: Delete a session on the server
      responses:
        204:
          description: Successfully deleted the session
        500:
          description: Error deleting the session
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /sessions/{sessionID}/refresh:
    put:
      tags:
        - sessions
      parameters:
        - name: sessionID
          in: path
          required: true
          schema:
            type: string
      description: Refresh the session extending its time to live
      responses:
        204:
          description: Successfully refreshed the session
        500:
          description: Error refreshing the session
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /envs:
    post:
      tags:
        - envs
      responses:
        200:
          description: Successfully created an environment
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewEnvironment"
  /envs/{codeSnippetID}:
    get:
      tags:
        - envs
      parameters:
        - name: codeSnippetID
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Environment"
  /envs/{codeSnippetID}/status:
    post:
      tags:
        - envs
      parameters:
        - name: codeSnippetID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnvironmentStatus"
