name: CLI

on:
  workflow_call:
    secrets:
      node_auth_token:
        required: true

jobs:
  publish:
    name: Build and publish CLI to NPM
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # TODO: Create proper monorepo
      - name: Setup local SDK dependency
        working-directory: ./packages/sdk
        run: |
          npm i && npm run build

      - name: Publish package
        run: pnpm publish
        working-directory: ./packages/cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.node_auth_token }}
