name: Devbook Daemon

on:
  workflow_call:
    secrets:
      github_token:
        required: true

jobs:
  publish:
    name: Build and release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          workdir: ./packages/devbookd
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
