name: Devbookd

on:
  workflow_call:
    secrets:
      service_account_email:
        required: true
      workload_identity_provider:
        required: true
      version:
        required: true

jobs:
  publish:
    name: Build, upload and release (releasing is disabled right now)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ./packages/devbookd/go.mod
          cache: true
          cache-dependency-path: ./packages/devbookd/go.sum

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          workdir: ./packages/devbookd
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ github.token  }}
          GORELEASER_CURRENT_TAG: ${{ secrets.version }}

      - name: Setup Service Account
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          service_account: ${{ secrets.service_account_email }}

      - name: Upload devbookd
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: './packages/devbookd/dist/devbookd_linux_amd64_v1/devbookd'
          destination: 'devbook-environment-pipeline'
