name: Orchestration Services - Environments

on:
  workflow_call:
    inputs:
      service_account_email:
        required: true
        type: string
      workload_identity_provider:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: Auth
        uses: google-github-actions/auth@v0
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account_email }}
