name: Orchestration Services - Environments

on:
  workflow_call:
    secrets:
      service_account_email:
        required: true
      workload_identity_provider:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Update
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: Auth
        uses: google-github-actions/auth@v0
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          service_account: ${{ secrets.service_account_email }}
