name: FC env

on:
  workflow_call:
    secrets:
      service_account_email:
        required: true
      workload_identity_provider:
        required: true

jobs:
  publish:
    name: Publish envs' pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Service Account
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          service_account: ${{ secrets.service_account_email }}

      # Takes cca 19s - cache system wide
      - name: Setup GCloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Package and upload pipelines
        working-directory: ./packages/fc-env
        run: make publish
