name: FC Kernels

on:
  push

jobs:
  publish:
    name: Upload kernels
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Service Account
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          service_account: ${{ secrets.service_account_email }}

      - name: Build kernels
        working-directory: ./packages/fc-kernels
        run: make build

      - name: Upload prebuilt kernels
        working-directory: ./packages/fc-kernels
        run: make upload
        env:
          GCP_PROJECT_ID: ${{ secrets.gcp_project_id }}

