name: Orchestration Services - Infrastructure

on:
  workflow_call:
    inputs:
      service_account_email:
        required: true
        type: string
      workload_identity_provider:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: Auth
        uses: google-github-actions/auth@v0
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account_email }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: infra
        run: make init

      - name: Terraform Plan
        working-directory: infra
        run: make plan

      - name: Terraform Apply
        working-directory: infra
        run: make deploy
