# name: Orchestration Services - Infrastructure

# on:
#   push:
#     branches:
#       - master
#     paths:
#       - infra/**
#       - .github/workflows/infra.yml

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   deploy:
#     name: Build
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - id: Auth
#         uses: google-github-actions/auth@v0
#         with:
#           create_credentials_file: true
#           workload_identity_provider: projects/424909584475/locations/global/workloadIdentityPools/github-actions/providers/github
#           service_account: github-action@devbookhq.iam.gserviceaccount.com

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2

#       - name: Terraform Init
#         working-directory: infra
#         run: make init

#       - name: Terraform Plan
#         working-directory: infra
#         run: make plan

#       - name: Terraform Apply
#         working-directory: infra
#         run: make deploy
