# name: Deploy Terraform on GCP

# on:
#   push:
#     branches:
#       - master
#     paths:
#       - infra/**
#       - .github/workflows/infra.yml

# env:
#   PROJECT_ID: ${{ secrets.GCE_PROJECT }}
#   GCE_IMAGE: orchestration-api

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   deploy:
#     name: Build
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - id: Auth
#         uses: "google-github-actions/auth@v0"
#         with:
#           workload_identity_provider: "projects/424909584475/locations/global/workloadIdentityPools/github-actions/providers/github"
#           service_account: "github-action@devbookhq.iam.gserviceaccount.com"

#       - name: "Set up Cloud SDK"
#         uses: "google-github-actions/setup-gcloud@v0"

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2

#       - name: Init Terraform
#         run: terraform init

#       - name: Terraform Format
#         run: terraform fmt -check

#       - name: Terraform Plan
#         run: terraform plan

#       - name: Terraform Apply
#         run: terraform apply -auto-approve
