# name: Orchestration Services

# on:
#   push:
#     branches:
#       - master

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   changes:
#     name: Check repo changes
#     runs-on: ubuntu-20.04
#     outputs:
#       orchestrator_image: ${{ steps.filter.outputs.orchestrator_image }}
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Check changes
#         uses: dorny/paths-filter@v2
#         id: filter
#         with:
#           filters: |
#             orchestrator_image:
#               - 'modules/orchestrator/orchestrator-image/**'
#               - '.github/workflows/orchestrator-image.yml'
#               - '.github/workflows/master.yml'
#   orchestrator_image:
#     name: Orchestrator image
#     needs: changes
#     if: ${{ needs.changes.outputs.orchestrator_image == 'true' }}
#     uses: ./.github/workflows/orchestrator-image.yml
#     secrets:
#       workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
#       service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

#   infrastructure:
#     name: Infrastructure
#     needs: [changes, api_image, orchestrator_image]
#     if: ${{ always() }}
#     uses: ./.github/workflows/infrastructure.yml
#     secrets:
#       workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
#       service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
