# name: Orchestration Services

# on:
#   push:
#     branches:
#       - master

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   changes:
#     name: Check repo changes
#     runs-on: ubuntu-20.04
#     outputs:
#       cluster_disk_image: ${{ steps.filter.outputs.cluster_disk_image }}
#       api_image: ${{ steps.filter.outputs.api_image }}
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Check changes
#         uses: dorny/paths-filter@v2
#         id: filter
#         with:
#           filters: |
#             cluster_disk_image:
#               - 'cluster/disk-image/**'
#               - '.github/workflows/cluster-disk-image.yml'
#               - '.github/workflows/master.yml'
#             api_image:
#               - 'api/**'
#               - '.github/workflows/api-image.yml'
#               - '.github/workflows/master.yml'
#   cluster_disk_image:
#     name: Cluster disk image
#     needs: changes
#     if: ${{ needs.changes.outputs.cluster_disk_image == 'true' }}
#     uses: ./.github/workflows/cluster-disk-image.yml
#     secrets:
#       workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
#       service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

#   api_image:
#     name: API image
#     needs: changes
#     if: ${{ needs.changes.outputs.api_image == 'true' }}
#     uses: ./.github/workflows/api-image.yml
#     secrets:
#       workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
#       service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

#   terraform:
#     name: Terraform
#     needs: [changes, api_image, cluster_disk_image]
#     if: ${{ always() }}
#     uses: ./.github/workflows/terraform.yml
#     secrets:
#       workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
#       service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
