name: Orchestration Services

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  changes:
    name: Check repo changes
    runs-on: ubuntu-20.04
    outputs:
      api: ${{ steps.filter.outputs.api }}
      orch: ${{ steps.filter.outputs.orch }}
      envs: ${{ steps.filter.outputs.envs }}
      infra: ${{ steps.filter.outputs.infra }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api:
              - 'api/**'
              - '.github/workflows/api.yml'
              - '.github/workflows/master.yml'
            orch:
              - 'orch/**'
              - '.github/workflows/orch.yml'
              - '.github/workflows/master.yml'
            envs:
              - 'envs/**'
              - '.github/workflows/envs.yml'
              - '.github/workflows/master.yml'
            infra:
              - 'envs/**'
              - '.github/workflows/infra.yml'
              - '.github/workflows/master.yml'

  api:
    name: API
    needs: changes
    if: ${{ needs.changes.outputs.api == 'true' }}
    uses: ./.github/workflows/api.yml
    with:
      project_id: devbookhq
      image_name: orchestration-api
    secrets:
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

  orch:
    name: Orchestrator
    needs: changes
    if: ${{ needs.changes.outputs.orch == 'true' }}
    uses: ./.github/workflows/orch.yml
    secrets:
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

  envs:
    name: Environments
    needs: changes
    if: ${{ needs.changes.outputs.envs == 'true' }}
    uses: ./.github/workflows/envs.yml
    secrets:
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

  # infra:
  #   name: Infrastructure
  #   needs: [changes, api, orch, envs]
  #   if: ${{ needs.changes.outputs.api == 'true' || needs.changes.outputs.orch == 'true' || needs.changes.outputs.envs == 'true' || needs.changes.outputs.infra == 'true' }}
  #   uses: ./.github/workflows/infra.yml
  #   secrets:
  #     workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  #     service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
