name: Measure performance

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */12 * * *
jobs:
  measure:
    name: Measure SDK performance
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm run build
      - run: CODE_SNIPPET_ID=Nodejs SUMMARY_FILE=$GITHUB_STEP_SUMMARY npm run measure
