# Estimated time 2m 40s
name: Orchestration Services - Orchestrator

on:
  push:
    branches:
      - master
    paths:
      - orch/**
      - .github/workflows/orch.yml

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: Auth
        uses: google-github-actions/auth@v0
        with:
          create_credentials_file: true
          workload_identity_provider: projects/424909584475/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: github-action@devbookhq.iam.gserviceaccount.com

      - name: Install Packer
        uses: hashicorp-contrib/setup-packer@v1

      - name: Build the image on GCE
        working-directory: orch
        run: |-
          make build
