name: Orchestration Services - Orchestrator

on:
  workflow_call:
    secrets:
      service_account_email:
        required: true
      workload_identity_provider:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: Auth
        uses: google-github-actions/auth@v0
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          service_account: ${{ secrets.service_account_email }}

      - name: Install Packer
        uses: hashicorp-contrib/setup-packer@v1

      - name: Initialize Packer plugins
        working-directory: orch
        run: |-
          make init

      - name: Build the image on GCE VM and save it on GCP
        working-directory: orch
        run: |-
          make build
