name: Run tests on PRs
on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          go-version-file: go.mod
      # Check out this article, btw. https://danp.net/posts/github-actions-go-cache
      - name: Cache Go dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod # actually uses `go env GOMODCACHE` output
            ~/.cache/go-build # actually uses `go env GOCACHE` output
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - name: Run tests
        run: make test
