name: Run tests on PRs
on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          go-version-file: go.mod
      - name: Cache Go dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod  # Uses `go env GOMODCACHE`
            ~/.cache/go-build  # Uses `go env GOCACHE`
          key: ${{ runner.os }}-golang-${{ hashFiles('packages/**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - name: Run tests
        run: make test
