name: Terraform

on:
  workflow_call:
    secrets:
      service_account_email:
        required: true
      workload_identity_provider:
        required: true
      server_cluster_size:
        required: true
      server_machine_type:
        required: true
      client_cluster_size:
        required: true
      client_machine_type:
        required: true

env:
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Service Account
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          service_account: ${{ secrets.service_account_email }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9

      - name: Create Terraform Plugin Cache Dir
        run: mkdir --parents $TF_PLUGIN_CACHE_DIR

#      - name: Cache Terraform
#        uses: actions/cache@v3
#        with:
#          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
#          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Init Terraform
        run: make init

      - name: Deploy Terraform
        run: make apply
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLIENT_MACHINE_TYPE: ${{ secrets.client_machine_type }}
          CLIENT_CLUSTER_SIZE: ${{ secrets.client_cluster_size }}
          SERVER_MACHINE_TYPE: ${{ secrets.server_machine_type }}
          SERVER_CLUSTER_SIZE: ${{ secrets.server_cluster_size }}
